api-version: 1.19
description: KnockIT by nerotvlive
version: '${project.version}'
website: https://nerotv.live/knockit
author: nerotvlive
main: live.nerotv.knockit.Main
name: KnockIT

depend:
  - ZyneonAPI

commands:
  Build:
  Ping:
  Warp:
    aliases: [warps,warp]
  World:
    aliases: [map,maps,worlds]
  GameMode:
    aliases: [gm,mode]
  ChangeMap:
  Shop:
  Rank:
  Disconnect:
    aliases: [disc,dc]